// <auto-generated />
using System;
using JobFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JobFlowDbContext))]
    [Migration("20250315193739_AddFireBaseUiColumn")]
    partial class AddFireBaseUiColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobFlow.Domain.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobStatusId");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("JobFlow.Domain.Models.JobStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("878f4fa0-e7c4-4440-bf7e-e1bdf068b551"),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("0e58e058-c9b8-4acf-b8ca-cb8d2eb857f4"),
                            Status = "Canceled"
                        },
                        new
                        {
                            Id = new Guid("5788453f-4c21-4c9b-b50c-f987c15d0cf2"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = new Guid("001a1323-185b-4624-987c-325b23bdb5c7"),
                            Status = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("0e48efd2-5783-4ea0-b091-6b4bf4377e38"),
                            Status = "On Hold"
                        },
                        new
                        {
                            Id = new Guid("be7d4999-e30f-4d4a-8f8b-580344e14dcd"),
                            Status = "Failed"
                        },
                        new
                        {
                            Id = new Guid("1ca909ea-e3e8-4364-a81f-7c5b93d9bc25"),
                            Status = "Awaiting Approval"
                        });
                });

            modelBuilder.Entity("JobFlow.Domain.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasFreeAccount")
                        .HasColumnType("bit");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeConnectedAccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StripeCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationTypeId");

                    b.HasIndex("StripeCustomerId");

                    b.ToTable("Organization", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d464b178-a52d-440b-a064-42246f7e0756"),
                            EmailAddress = "jerry.daniel.phillips@gmail.com",
                            HasFreeAccount = true,
                            OrganizationName = "Katharix",
                            OrganizationTypeId = new Guid("6ac2cabc-bbe3-4bc1-9879-5455de042cf4")
                        },
                        new
                        {
                            Id = new Guid("b3b20208-07ae-40a2-971e-adf3bb93fc8c"),
                            Address1 = "116 Terrill St",
                            City = "Beckley",
                            EmailAddress = "vonbrown230@gmail.com",
                            HasFreeAccount = true,
                            OrganizationName = "Browns Cleaning Services",
                            OrganizationTypeId = new Guid("1921d982-22f8-4ed5-b4e3-fca82c5767eb"),
                            PhoneNumber = "304-731-1952",
                            State = "WV",
                            ZipCode = "25801"
                        });
                });

            modelBuilder.Entity("JobFlow.Domain.Models.OrganizationClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StripeCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("StripeCustomerId");

                    b.ToTable("OrganizationClient", (string)null);
                });

            modelBuilder.Entity("JobFlow.Domain.Models.OrganizationClientJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("JobId", "OrganizationClientId");

                    b.HasIndex("OrganizationClientId");

                    b.ToTable("OrganizationClientJob", (string)null);
                });

            modelBuilder.Entity("JobFlow.Domain.Models.OrganizationService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationService", (string)null);
                });

            modelBuilder.Entity("JobFlow.Domain.Models.OrganizationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrganizationType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf489aa6-db19-42df-82bc-c116bd967e7e"),
                            TypeName = "General Contracting"
                        },
                        new
                        {
                            Id = new Guid("393a5b3e-323e-4b76-aa86-0d4683ddcd49"),
                            TypeName = "Painting"
                        },
                        new
                        {
                            Id = new Guid("e01750b0-0d01-4e25-abf7-6efa23509035"),
                            TypeName = "Plumbing"
                        },
                        new
                        {
                            Id = new Guid("fbc6accf-0fb1-4908-b449-14f13b826f24"),
                            TypeName = "Landscaping and Gardening"
                        },
                        new
                        {
                            Id = new Guid("9362c957-0f41-4c20-9085-c01e449fdda2"),
                            TypeName = "Electrical Services"
                        },
                        new
                        {
                            Id = new Guid("8f0d3e93-425b-4a53-b4d2-4c5eb97e490f"),
                            TypeName = "Carpentry and Woodworking"
                        },
                        new
                        {
                            Id = new Guid("37fc17e8-0a25-4119-9a71-7d160bb9c7b4"),
                            TypeName = "HVAC Services"
                        },
                        new
                        {
                            Id = new Guid("f64f078f-ecfb-4f3e-8640-236219fcf01e"),
                            TypeName = "Tree Removal"
                        },
                        new
                        {
                            Id = new Guid("bf3b9512-8a9c-4a73-9f88-cb914c1573cd"),
                            TypeName = "Pest Control"
                        },
                        new
                        {
                            Id = new Guid("1921d982-22f8-4ed5-b4e3-fca82c5767eb"),
                            TypeName = "Cleaning Services"
                        },
                        new
                        {
                            Id = new Guid("408d2185-53b9-493d-8713-938114de90f5"),
                            TypeName = "Junk Removal"
                        },
                        new
                        {
                            Id = new Guid("33341b2d-957f-4efb-94f7-3a015ae1a718"),
                            TypeName = "Car Detailing"
                        },
                        new
                        {
                            Id = new Guid("30530a32-a151-436d-a050-613eac4c22d5"),
                            TypeName = "IT & Network Installation"
                        },
                        new
                        {
                            Id = new Guid("6ac2cabc-bbe3-4bc1-9879-5455de042cf4"),
                            TypeName = "Master Account"
                        });
                });

            modelBuilder.Entity("JobFlow.Domain.Models.StripeCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Delinqent")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StripeCustomer", "payment");
                });

            modelBuilder.Entity("JobFlow.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e88fbbe6-8bdf-4aca-b941-912785a94f0b"),
                            Name = "Organization Admin",
                            NormalizedName = "ORGANIZATION ADMIN"
                        },
                        new
                        {
                            Id = new Guid("079e4277-0eb2-4222-82e4-5a751ede48f6"),
                            Name = "Organization Employee",
                            NormalizedName = "ORGANIZATION EMPLOYEE"
                        },
                        new
                        {
                            Id = new Guid("3da14c58-562a-437a-a2a6-47706b40eb70"),
                            Name = "Organization Client",
                            NormalizedName = "ORGANIZATION CLIENT"
                        },
                        new
                        {
                            Id = new Guid("5bc0d325-a915-4e17-8184-428ee533cf89"),
                            Name = "Katharix Admin",
                            NormalizedName = "KATHARIX ADMIN"
                        },
                        new
                        {
                            Id = new Guid("92193eb2-dba0-433c-814e-9fca95bde016"),
                            Name = "Katharix Employee",
                            NormalizedName = "KATHARIX EMPLOYEE"
                        },
                        new
                        {
                            Id = new Guid("dfe36ebc-bfb5-4583-b68e-59be8ba60fa9"),
                            Name = "Super Admin",
                            NormalizedName = "SUPER ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("JobFlow.Domain.Models.Job", b =>
                {
                    b.HasOne("JobFlow.Domain.Models.JobStatus", "JobStatus")
                        .WithMany()
                        .HasForeignKey("JobStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobStatus");
                });

            modelBuilder.Entity("JobFlow.Domain.Models.Organization", b =>
                {
                    b.HasOne("JobFlow.Domain.Models.OrganizationType", "OrganizationType")
                        .WithMany()
                        .HasForeignKey("OrganizationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobFlow.Domain.Models.StripeCustomer", "StripeCustomer")
                        .WithMany()
                        .HasForeignKey("StripeCustomerId");

                    b.Navigation("OrganizationType");

                    b.Navigation("StripeCustomer");
                });

            modelBuilder.Entity("JobFlow.Domain.Models.OrganizationClient", b =>
                {
                    b.HasOne("JobFlow.Domain.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobFlow.Domain.Models.StripeCustomer", "StripeCustomer")
                        .WithMany()
                        .HasForeignKey("StripeCustomerId");

                    b.Navigation("Organization");

                    b.Navigation("StripeCustomer");
                });

            modelBuilder.Entity("JobFlow.Domain.Models.OrganizationClientJob", b =>
                {
                    b.HasOne("JobFlow.Domain.Models.Job", "Job")
                        .WithMany("OrganizationClientJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFlow.Domain.Models.OrganizationClient", "OrganizationClient")
                        .WithMany("OrganizationClientJobs")
                        .HasForeignKey("OrganizationClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("OrganizationClient");
                });

            modelBuilder.Entity("JobFlow.Domain.Models.OrganizationService", b =>
                {
                    b.HasOne("JobFlow.Domain.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("JobFlow.Domain.Models.User", b =>
                {
                    b.HasOne("JobFlow.Domain.Models.OrganizationClient", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("JobFlow.Domain.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("JobFlow.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("JobFlow.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFlow.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("JobFlow.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobFlow.Domain.Models.Job", b =>
                {
                    b.Navigation("OrganizationClientJobs");
                });

            modelBuilder.Entity("JobFlow.Domain.Models.OrganizationClient", b =>
                {
                    b.Navigation("OrganizationClientJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
