import { test, expect } from '@playwright/test';
import { authJson, unwrapResult } from '../support/api-client';
import { hasBearerToken, requireBearerToken } from '../support/config';

type OrganizationClientDto = {
  id: string;
  organizationId?: string;
  firstName?: string;
  lastName?: string;
  emailAddress?: string;
};

type EstimateDto = {
  id: string;
  organizationClientId: string;
  title?: string;
};

type JobDto = {
  id: string;
  title?: string;
  organizationClientId: string;
  estimateId?: string;
};

type InvoiceDto = {
  id: string;
  jobId: string;
  organizationClientId: string;
  invoiceNumber: string;
};

test.describe('Business flow API E2E', () => {
  test.skip(!hasBearerToken(), 'Requires JOBFLOW_API_BEARER_TOKEN for authenticated flow.');

  test('create client -> create estimate -> upsert job -> create invoice', async ({ request }) => {
    const bearerToken = requireBearerToken();
    const stamp = Date.now();
    const clientEmail = `e2e-client-${stamp}@example.test`;

    const clientPayload = {
      firstName: 'E2E',
      lastName: `Client-${stamp}`,
      emailAddress: clientEmail,
      phoneNumber: '555-0100',
      city: 'Austin',
      state: 'TX',
      zipCode: '73301'
    };

    const upsertClientRaw = await authJson<unknown>(
      request,
      'post',
      '/api/organization/clients/upsert',
      bearerToken,
      clientPayload
    );
    const createdClient = unwrapResult<OrganizationClientDto>(upsertClientRaw);

    expect(createdClient.id).toBeTruthy();
    expect((createdClient.emailAddress ?? '').toLowerCase()).toBe(clientEmail.toLowerCase());

    const estimatePayload = {
      organizationClientId: createdClient.id,
      title: `E2E Estimate ${stamp}`,
      description: 'Automation estimate',
      notes: 'Generated by Playwright business-flow suite',
      lineItems: [
        {
          name: 'Diagnostic Visit',
          description: 'Initial site visit',
          quantity: 1,
          unitPrice: 95.0
        },
        {
          name: 'Labor',
          description: 'Repair work',
          quantity: 2,
          unitPrice: 120.0
        }
      ]
    };

    const createdEstimate = await authJson<EstimateDto>(
      request,
      'post',
      '/api/estimates',
      bearerToken,
      estimatePayload
    );

    expect(createdEstimate.id).toBeTruthy();
    expect(createdEstimate.organizationClientId).toBe(createdClient.id);

    const jobPayload = {
      title: `E2E Job ${stamp}`,
      comments: 'Created from e2e estimate',
      lifecycleStatus: 0,
      organizationClientId: createdClient.id,
      estimateId: createdEstimate.id
    };

    const upsertedJob = await authJson<JobDto>(
      request,
      'post',
      '/api/job/upsert',
      bearerToken,
      jobPayload
    );

    expect(upsertedJob.id).toBeTruthy();
    expect(upsertedJob.organizationClientId).toBe(createdClient.id);

    const invoicePayload = {
      organizationId: process.env.JOBFLOW_ORGANIZATION_ID ?? '00000000-0000-0000-0000-000000000000',
      jobId: upsertedJob.id,
      dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      lineItems: [
        {
          description: 'Labor & Materials',
          quantity: 1,
          unitPrice: 335,
          lineTotal: 335
        }
      ]
    };

    const createdInvoice = await authJson<InvoiceDto>(
      request,
      'post',
      '/api/invoice/organization',
      bearerToken,
      invoicePayload
    );

    expect(createdInvoice.id).toBeTruthy();
    expect(createdInvoice.jobId).toBe(upsertedJob.id);
    expect(createdInvoice.organizationClientId).toBe(createdClient.id);
    expect(createdInvoice.invoiceNumber).toBeTruthy();

    const fetchedInvoice = await authJson<InvoiceDto>(
      request,
      'get',
      `/api/invoice/${createdInvoice.id}`,
      bearerToken
    );

    expect(fetchedInvoice.id).toBe(createdInvoice.id);
    expect(fetchedInvoice.jobId).toBe(upsertedJob.id);
  });
});
